version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: bcbsal_us_en_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    container_name: bcbsal_us_en_wp
    depends_on:
      - db
    image: wordpress:php8.0-apache
    volumes:
      - ./wp-content/themes/:/var/www/html/wp-content/themes/:rw
      - ./wp-content/mu-plugins/:/var/www/html/wp-content/mu-plugins/:rw
    ports:
      - '8080:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_DATABASE: wordpress
